config/routes.rb
Fff::Application.routes.draw do
  resources :feedbacks

  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_one :feedback, :dependent => :destroy
  validates_presence_of :name
  before_save :init_feedback
  
  def init_feedback
    self.feedback = Feedback.create
    feedback.save
  end 
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :events
  
  def feast
    feast = self.read_attribute(:feast)
    return feast if feast
    self.feast = 0
  end
  
  def famine
    famine = self.read_attribute(:famine)
    return famine if famine
    self.famine = 0
  end
  
  def members_only
    members_only = self.read_attribute(:members_only)
    return members_only if members_only
    self.members_only = 0
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/events/_feedback.haml
.feedback-title
	="Feedback"

%table
	%tr.titles
		%td.feast
			="Feasting:"
		%td.famine
			="Famished:"
		%td.members_only
			="\"Members Only\":"
	%tr.stats
		%td.feast
			= "#{feedback.feast}"
		%td.famine
			= "#{feedback.famine}"
		%td.members_only
			= "#{feedback.members_only}"

app/views/events/_form.html.haml
= form_for(@event) do |f|
	-if @event.errors.any?
		#error_explanation
			%h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
			%ul
				- @event.errors.full_messages.each do |msg|
					%li= msg
					
	.field
		=f.label :name
		%br
		=f.text_field :name
	.field
		=f.label :street1
		%br
		=f.text_field :street1
	.field
		=f.label :street2
		%br
		=f.text_field :street2
	.field
		=f.label :city
		%br
		=f.text_field :city
	.field
		=f.label :state
		%br
		=f.text_field :state
	.field
		=f.label :zip_code
		%br
		=f.text_field :zip_code
	.field
		=f.label :start_time
		%br
		=f.datetime_select :start_time
	.field
		=f.label :start_time
		%br
		=f.datetime_select :end_time

	.actions
		=f.submit
		
	

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Events

%table
	%tr
		%th Name
		%th Street1
		%th Street2
		%th City
		%th State
		%th Zip code
		%th Start time
		%th End time
		%th
		%th
		%th


	-@events.each do |event|
		%tr
			%td= event.name
			%td= "#{event.street1} #{" "+event.street2 if event.street2}\n#{event.zip_code}" 
			%td= event.state
			%td= event.zip_code
			%td= event.start_time
			%td= event.end_time
			%td= link_to 'Show', event
			%td= link_to 'Edit', edit_event_path(event)
			%td= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete

= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New event

= render 'form'
	
= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice
%p
	%b Name:
	= @event.name
%p
	%b Street1:
	= @event.street1
%p
	%b Street2:
	= @event.street2
%p
	%b City:
	= @event.city
%p
	%b State:
	= @event.state
%p
	%b Zip code:
	= @event.zip_code
%p
	%b Start time:
	= @event.start_time
%p
	%b End time:
	= @event.end_time

%p
	= render :partial => "feedback", :locals => {:feedback => @event.feedback }

= link_to 'Edit', edit_event_path(@event) |
= link_to 'Back', events_path

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.text_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :feast %><br />
    <%= f.text_field :feast %>
  </div>
  <div class="field">
    <%= f.label :famine %><br />
    <%= f.text_field :famine %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Feast</th>
    <th>Famine</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.event_id %></td>
    <td><%= feedback.feast %></td>
    <td><%= feedback.famine %></td>
    <td><%= link_to 'Show', feedback %></td>
    <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
    <td><%= link_to 'Destroy', feedback, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @feedback.event_id %>
</p>

<p>
  <b>Feast:</b>
  <%= @feedback.feast %>
</p>

<p>
  <b>Famine:</b>
  <%= @feedback.famine %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fff</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="banner">
		<%= image_tag("no_money.jpg", :size => "50x50") %>
		<%= image_tag("pizza.jpg", :size => "50x50") %>
		<span id="title"><%= @page_title || "Free Food Finder" %></span>
		<%= image_tag("pizza.jpg", :size => "50x50") %>
		<%= image_tag("no_money.jpg", :size => "50x50") %>
	</div>

<%= yield %>

</body>
</html>